-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public." job_positions"
(
    id integer NOT NULL,
    "position" character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employees
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(100) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    web_address character varying(100) NOT NULL,
    phone_number character varying(11) NOT NULL,
    is_activated bit(1) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers_activation_code
(
    id integer NOT NULL,
    employer_user_id integer NOT NULL,
    activation_code character varying(10) NOT NULL,
    is_confirmed bit(1) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers_activation_employees
(
    id integer NOT NULL,
    employer_user_id integer NOT NULL,
    confirmed_employee_user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.candidates (user_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employees (user_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.employers_activation_code (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.employers_activation_employees (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.employers_activation_employees (id)
    NOT VALID;

END;